# Generated by Django 3.2.9 on 2021-12-09 14:38

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('chat_id', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=200, null=True)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('token', models.CharField(default=myapp.models.make_token, max_length=255)),
                ('confirmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.employee')),
            ],
            options={
                'verbose_name': 'Xodimlar',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RequestTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('template', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmers', models.ManyToManyField(related_name='Tasdiqlovchilar', to='myapp.Employee')),
                ('groups', models.ManyToManyField(blank=True, null=True, to='myapp.Group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('template', models.TextField()),
                ('desc', models.TextField(null=True)),
                ('confirmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tasdiqlovchi', to='myapp.employee')),
                ('req_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.requesttypes')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Yuboruvchi', to='myapp.employee')),
            ],
        ),
    ]
