# Generated by Django 3.2.9 on 2021-12-01 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('chat_id', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=200, null=True)),
                ('desc', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.employee')),
            ],
            options={
                'verbose_name': 'Xodimlar',
                'db_table': 'Xodimlar',
            },
        ),
        migrations.CreateModel(
            name='RequestTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('template', models.TextField()),
                ('confirmer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tasdiqlagan_odam', to='myapp.employee')),
                ('confirmers', models.ManyToManyField(related_name='Tasdiqlovchilar', to='myapp.Employee')),
                ('req_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.requesttypes')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Yuboruvchi', to='myapp.employee')),
            ],
        ),
    ]
