# Generated by Django 3.2.9 on 2021-12-02 11:46

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_employee_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='token',
            field=models.CharField(default=myapp.models.make_token, max_length=255),
        ),
    ]
