# Generated by Django 3.2.9 on 2021-12-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_requests_confirmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttypes',
            name='template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
