# Generated by Django 3.2.9 on 2021-12-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_requesttypes_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='confirm_date',
            field=models.DateTimeField(null=True),
        ),
    ]
