# Generated by Django 3.2.9 on 2021-12-04 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_requests_confirm_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
