# Generated by Django 3.2.9 on 2021-12-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_requests_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='confirm_date',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='confirmers',
        ),
        migrations.AddField(
            model_name='requesttypes',
            name='confirmers',
            field=models.ManyToManyField(related_name='Tasdiqlovchilar', to='myapp.Employee'),
        ),
        migrations.AddField(
            model_name='requesttypes',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.Group'),
        ),
    ]
