# Generated by Django 3.2.9 on 2021-12-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_group_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='confirm_date',
            field=models.DateTimeField(null=True),
        ),
    ]
