# Generated by Django 3.2.9 on 2021-12-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_requests_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='created_at',
            field=models.CharField(blank=True, default='18.12.2021 16:24', max_length=100, null=True),
        ),
    ]
